version: '3.9'
services:
  postgres:
    container_name: "uptrader_postgres"
    image: postgres:14.4
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    env_file:
      - ./.env
  web:
    build: ./web
    volumes:
      - ./web:/web
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
    links:
      - postgres:postgres

