# Generated by Django 4.2 on 2023-05-08 23:52

from django.db import migrations
from django.core.management import call_command

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'fixtures/menu.json')

class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]
